### ISSUE TITLE
[enhancement] Is it more convinient to implement this with Github Action?

### ISSUE THREAD

**Issue by BobAnkh** [banzai200/Github-Help-Wanted#2]
Providing GITHUB_TOKEN to PyGithub which may increase the limits.

I think it's interesting to search these issues and write them to a file using PyGithub with Github Action.

**Comment by banzai200** [comment]
> Providing GITHUB_TOKEN to PyGithub which may increase the limits.

That's actually one of the things that i want to do on the next commits, i will integrate using an argument

> I think it's interesting to search these issues and write them to a file using PyGithub with Github Action.

 You mean, use Github Action to write the output on a file instead of stdout?

**Comment by BobAnkh** [comment]
> That's actually one of the things that i want to do on the next commits, i will integrate using an argument

If you haven't implemented it yet, I think I can help to do this.

> You mean, use Github Action to write the output on a file instead of stdout?

Yes, I mean to upload these results using PyGithub. But maybe this is not suitable to implement here? As for me, I think it is more convenient to configure a action to search these issues and return a file for me to look up. And I think just providing a option to write the results into a file is a good idea.(have you already supported this?) And more options can be supported, like just returning opening ones.

And may be the documentation should be refactored? :joy:

If you have interests to improve it I can be there to help.

**Comment by banzai200** [comment]
I would love some help, especially with the documentation

> And I think just providing a option to write the results into a file is a good idea.(have you already supported this?)

I didn't thought of it being a whole thing, just of using stdout to file redirection like: ```gh [arguments] > file.md```

**Comment by BobAnkh** [comment]
> I would love some help, especially with the documentation

I would like to help with documentaion. But could you tell me more about your plan of doing that? And could I just start with adding docstring to each function to explain its arguments?

**Comment by banzai200** [comment]
> And could I just start with adding docstring to each function to explain its arguments?

Sure!

> But could you tell me more about your plan of doing that?

I'm gonna add another argument adding the option of using the login/access token on the input
